export enum BucketActionTypes {
  ADD_BUCKET_ITEM  = "bucket/ADD_BUCKET_ITEM",
  REMOVE_BUCKET_ITEM = 'bucket/REMOVE_BUCKET_ITEM',
  CLEAR_BUCKET = 'bucket/CLEAR_BUCKET',
  UPDATE_BUCKET_ITEM = 'bucket/UPDATE_BUCKET_ITEM',
  UPDATE_BUCKET_ITEM_INDEX = 'bucket/UPDATE_BUCKET_ITEM_INDEX',
  SET_DELIVERY_CHARGE_AMOUNT = 'bucket/SET_DELIVERY_CHARGE_AMOUNT',
  SET_TIP_AMOUNT = 'bucket/SET_TIP_AMOUNT',
  RESET_BUCKET = 'bucket/RESET_BUCKET'
}
