export enum BucketActionTypes {
  ADD_BUCKET_ITEM  = "bucket/ADD_BUCKET_ITEM",
  REMOVE_BUCKET_ITEM = 'bucket/REMOVE_BUCKET_ITEM',
  CLEAR_BUCKET = 'bucket/CLEAR_BUCKET',
  UPDATE_BUCKET_ITEM = 'bucket/UPDATE_BUCKET_ITEM'
}
