export enum AuthTypes {
  CUSTOMER_LOGIN = "auth/CUSTOMER_LOGIN",
  CUSTOMER_LOGIN_SUCCESS = "auth/CUSTOMER_LOGIN_SUCCESS",
  CUSTOMER_LOGIN_FAILED = "auth/CUSTOMER_LOGIN_FAILED",
  CUSTOMER_LOGIN_CLEAR = 'auth/CUSTOMER_LOGIN_CLEAR',

  CUSTOMER_SIGNUP = "auth/CUSTOMER_SIGNUP",
  CUSTOMER_SIGNUP_SUCCESS = "auth/CUSTOMER_SIGNUP_SUCCESS",   // ✅ add
  CUSTOMER_SIGNUP_FAILED = "auth/CUSTOMER_SIGNUP_FAILED",     // ✅ add
  CUSTOMER_SIGNUP_CLEAR = "auth/CUSTOMER_SIGNUP_CLEAR",
}