import type { Metadata } from "next";
import type { ReactNode } from "react";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { RestaurantProvider } from "@/contexts/restaurant-context";
import { getRestaurantForRequest } from "@/lib/restaurant.server";
import "@/app/globals.css";

const geistSans = localFont({ src: "./fonts/GeistVF.woff", variable: "--font-geist-sans", weight: "100 900" });
const geistMono = localFont({ src: "./fonts/GeistMonoVF.woff", variable: "--font-geist-mono", weight: "100 900" });

export const metadata: Metadata = { title: "YummyWebiste", description: "Generated by next.js" };

export default async function Layout({ children }: { children: ReactNode }) {
  const restaurantData = await getRestaurantForRequest();
  console.log('restaurantData =>', restaurantData)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <RestaurantProvider value={restaurantData}>
            {/* Any component that reads the contextmust be a Client Component */}
            <Header />
            <main className="min-h-[48vh]">{children}</main>
            <Footer />
          </RestaurantProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
